name: lint
on: 
  pull_request:
  push:
    branches:
      - main

jobs:
  awesome-lint:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 0
      - name: "setup node"
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: "awesome-lint"
        run: npx -y awesome-lint ./readme-template.md
